
---
- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: Add Nodesource apt key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Add yarn repo key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "Yarn | Ensure Debian sources list file exists"
  file:
    path: /etc/apt/sources.list.d/yarn.list
    owner: root
    mode: 0644
    state: touch

- name: "Yarn | Ensure Debian package is in sources list"
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
    line: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: "Update APT cache"
  apt:
    update_cache: yes

- name: Ensure Node.js and yarn are installed.
  apt:
    state: present
    pkg:
      - "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
      - yarn

- name: Ensure yarn global packages are installed.
  yarn:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: True
    state: latest
  with_items: "{{ nodejs_yarn_global_packages }}"


- name: Install packages defined in a given package.json.
  yarn:
    path: "{{ nodejs_package_json_path }}"
  when: nodejs_package_json_path is defined and nodejs_package_json_path
